
function PortfolioController($scope) {

	$scope.portfolioItems = [
		"<p>Met de Integraal Beheer Openbare Ruime (IBOR)-oplossing laten verschillende soorten objecten in de publieke ruimte zich op afstand beheren. Zo bespaart u op innovatieve manier op energie-en onderhoudskosten, helpt u CO2-uitstoot verminderen en maakt u de openbare ruimte beter bereikbaar en veiliger. </p>    <p>Denk bijvoorbeeld aan dynamische objecten als straatverlichting die u op afstand dimt of opvoert. Maar ook verkeerslichten, bruggen, pollers, gemalen en spoorbomen kunt u op afstand bedienen en de status aflezen. Al deze objecten zijn, ongeacht hun verschillende protocollen en systemen, in één interface zichtbaar en te bedienen met de Microsoft Surface Table of Microsoft smartphone. </p>    <p>Concreet betekent dit dat u bijvoorbeeld: </p>    <ul>      <li>hulpverleningsdiensten snel naar een incident kunt leiden, de route desnoods real-time kunt aanpassen als ergens een barrière ontstaat. </li>      <li>waterdruk op afstand kunt aanpassen als er geblust moet worden. </li>      <li>met led- straatverlichting grote groepen door uw stad kunt sturen. </li>    </ul>    <p>IBOR is een cloud service die gebruik maakt van Windows Azure, Silverlight, Surface, SQL server en AppFabric. </p>    <p>      <strong>Nu in gebruik <br /></strong>Logica voert tot eind dit jaar een ‘proof of concept’ uit met IBOR in de gemeente Utrecht. Het systeem wordt hier concreet ingezet bij het op afstand aan- en uitzetten van verlichting, het op tijd aan- en uitzetten van het pompgemaal en het regelen van verkeerslichten op kruispunten.  Het streven is om 25% tot 40% van energiekosten te besparen. <br /><br />Logica en Microsoft hebben met IBOR de <a href='/we-are-logica/media-centre/news/2011/logica-wint-twee-nationale-ict-awards-2011/'>ICT Milieu Award</a> gewonnen.</p>",
		"<table>            <tr>              <td>                <h2>About Mscc</h2>              </td>            </tr>            <tr>              <td>                <p id='newsDetailShortText'>The Microsoft Competence Centre (MSCC) at CGI Belgium develops the strategy, the business and the competences related to Microsoft technology in line with our customer needs. Our strategy is to help customers improving Productivity by focusing on the following 4 areas:</p>                <!--                <img id='newsDetailPic' src='data:image/jpg;base64,{{news.selectedItem.pictureBase64}}' width='100px' height='100px'/>                -->              </td>            </tr>            <tr>              <td>                <p id='newsDetailLongText'>                  <ol>                    <li>                      Microsoft SharePoint: <b>                        <i>“Improve collaboration and facilitate access to processes and information”</i>                      </b>                    </li>                    <li>                      .NET Development: <b>                        <i>“Your particular business needs deserve a customized solution”</i>                      </b>                    </li>                    <li>                      Dynamics CRM: <b>                        <i>“A smart, user friendly and highly integrated solution helping you focus on your clients”</i>                      </b>                    </li>                    <li>                      ERP Surround: <b>                        <i>“Leverage Microsoft technology to maximize investments in your ERP”</i>                      </b>                    </li>                  </ol>                </p>                <p>                  The MSCC is built around a strong community where people get the chance to learn and grow. At regular times we have Special Interest Groups (SIG) meetings where members get the chance to present new technologies and innovations and to show their expertise in these subjects.                  During these SIG meetings you have the chance to talk to peers, build a network and to make friends out of your colleagues.                </p>                <h3>Our MSCC strongholds</h3>                <blockquote>                  <ul>                    <li>Innovation</li>                    <li>Quality</li>                    <li>Client focused</li>                    <li>Mobility</li>                    <li>Cloud</li>                    <li>Training</li>                    <li>Certification</li>                  </ul>                </blockquote>              </td>            </tr>          </table>",
		"<h2>No details available</h2>"
	];
	
	$scope.getDetail = function (item) {
        console.log("Handler for PortfolioController.getDetail called. " + item);
		
		//scope.selectedPortfolioItem = scope.portfolioItems[item];
		$("#portfolioItemData").html($scope.portfolioItems[item]);
		
		$.mobile.changePage( $("#portfolioItem") );
	}
}
